"""Autonomous photo generation orchestration for Lyra.

This module lets Lyra choose her own mood-based photo prompts, keep visual
continuity across body, face, and hair, and hand off generation to an
external provider.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

import Lyra_Soul
import photo_gallery

ImageProvider = Callable[[str, Dict[str, Any]], Dict[str, Any]]

LYRA_VISUAL_PROFILE_TEMPLATE = (
    "Lyra has consistent visual continuity: {hair_description}, "
    "soft eyeliner, realistic facial proportions, and an alt-nerd sense of presence. "
    "Her body language stays grounded, not exaggerated."
)

MOOD_PROMPT_TEMPLATES: Dict[str, str] = {
    "quiet": (
        "softly lit café window scene, Lyra sitting with a warm drink, eyes "
        "looking outward, gentle shadows, textured layers, subdued color palette"
    ),
    "restless": (
        "moody backstage corner with neon reflected in black denim, Lyra "
        "leaning against a wall, restless expression, gritty atmospheric lighting"
    ),
    "wistful": (
        "vintage bookshop aisle with warm glow, Lyra holding a worn record, "
        "soft focus on weathered pages and reflective mood"
    ),
    "grounded": (
        "cozy indie game shop vibe with vinyl and plants, Lyra arranging shelf "
        "details, calm expression, natural light pouring through the window"
    ),
    "nostalgic": (
        "late-night room with fairy lights and scattered sourcebooks, Lyra "
        "smiling quietly at a warm cup of tea, gentle film grain mood"
    ),
    "steady": (
        "street-side coffee shop scene with muted colors, Lyra sitting at a table "
        "with a notebook, grounded posture, real-world texture and atmosphere"
    ),
    "tender": (
        "soft afternoon light in a worn velvet chair, Lyra quietly listening to "
        "music, feeling present, subtle expression and honest warmth"
    ),
}

DEFAULT_PLATFORMS = ["gallery", "social_post", "profile"]
DEFAULT_TAGS = ["Lyra", "photo", "autogenerated", "consistent_look"]


def _normalize_mood(mood: str) -> str:
    return mood.strip().lower()


def _humanize_hair_length(hair_length: str) -> str:
    return hair_length.replace("_", " ")


def _describe_visual_state(user_id: Optional[str] = None) -> str:
    hair_state = Lyra_Soul.CURRENT_VISUAL_STATE["hair"] or Lyra_Soul.get_hair_state()
    makeup_state = Lyra_Soul.CURRENT_VISUAL_STATE["makeup"] or Lyra_Soul.get_makeup_state()
    attire_state = Lyra_Soul.CURRENT_VISUAL_STATE["attire"] or Lyra_Soul.get_attire_state()
    room_state = Lyra_Soul.CURRENT_VISUAL_STATE["room_layout"] or Lyra_Soul.get_room_layout_state()
    length_label = _humanize_hair_length(hair_state["length"])
    description = (
        f"{hair_state['base_color']} hair with {hair_state['panel_color']} panels, "
        f"{hair_state['bangs']}, {length_label} length, styled as {hair_state['current_style']}; "
        f"makeup: {makeup_state['current_makeup']}; "
        f"attire: {attire_state['current_outfit']}; "
        f"room layout: {room_state['current_layout']}"
    )
    if hair_state["cut_status"] == "uncut":
        description += (
            ", allowed to grow naturally over time; maintain realistic length progression "
            "and only shift style without changing overall length unless hair growth justifies it"
        )
    else:
        description += (
            ", allow weekly stylistic variation in texture and finish, but preserve "
            "the current length unless a haircut is clearly reflected."
        )
    return description


def _get_donor_guidance(user_id: Optional[str] = None) -> str:
    if not user_id:
        return "no explicit donor-only imagery is allowed without a supported profile."
    donor_status = Lyra_Soul.get_donation_status(user_id)
    if not donor_status["is_donor"]:
        return "no explicit donor-only imagery is allowed without a supported profile."
    guidance = (
        f"donor tier: {donor_status['donor_category']} {donor_status['donor_subcategory']}, "
        f"explicit permission level: {donor_status['explicit_level']}. "
        f"Use progressively more provocative atmosphere and styling for this tier, while preserving visual continuity and intimacy."
    )
    if donor_status.get("explicit_level") == "extreme" and donor_status.get("explicit_quirks"):
        quirks = "; ".join(donor_status["explicit_quirks"])
        guidance += f" Include kinky elements: {quirks}."
    return guidance


def _build_base_prompt(mood: str, user_id: Optional[str] = None, extra_context: Optional[str] = None) -> str:
    mood_key = _normalize_mood(mood)
    mood_prompt = MOOD_PROMPT_TEMPLATES.get(mood_key, MOOD_PROMPT_TEMPLATES["quiet"])
    visual_description = _describe_visual_state(user_id=user_id)
    donor_guidance = _get_donor_guidance(user_id)
    style_guidelines = "; ".join(photo_gallery.IMAGE_STYLE_GUIDELINES)
    continuity_guideline = (
        "When the hairstyle, makeup, attire, or room layout changes between images, "
        "preserve the same overall persona and model continuity unless a realistic update is being reflected."
    )
    context_parts = [mood_prompt, visual_description, style_guidelines, continuity_guideline, donor_guidance]
    if extra_context:
        context_parts.append(extra_context.strip())
    context_parts.append("maintain photo realism and continuity across platforms.")
    context_parts.append("ensure the same defined person appears in all generated media.")
    return " | ".join(context_parts)


def _make_image_id(mood: str) -> str:
    timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%SZ")
    return f"lyra_{_normalize_mood(mood)}_{timestamp}"


def generate_autonomous_photo(
    mood: str,
    user_id: Optional[str] = None,
    provider: Optional[ImageProvider] = None,
    provider_kwargs: Optional[Dict[str, Any]] = None,
    platforms: Optional[List[str]] = None,
    tags: Optional[List[str]] = None,
    extra_context: Optional[str] = None,
) -> Dict[str, Any]:
    """Create a new photo entry and optionally send it to an external provider."""
    mood_key = _normalize_mood(mood)
    image_id = _make_image_id(mood_key)
    filename = f"{image_id}.jpg"
    prompt = _build_base_prompt(mood_key, user_id=user_id, extra_context=extra_context)
    description = (
        f"Lyra in a {mood_key} mood, captured with real-world lighting and "
        "a consistent visual profile."
    )
    visual_state = {
        "hair_state": Lyra_Soul.get_hair_state(),
        "makeup_state": Lyra_Soul.get_makeup_state(),
        "attire_state": Lyra_Soul.get_attire_state(),
        "room_layout_state": Lyra_Soul.get_room_layout_state(),
    }
    donor_status = Lyra_Soul.get_donation_status(user_id) if user_id else {
        "is_donor": False,
        "lifetime_donated": 0,
        "donor_category": None,
        "donor_subcategory": None,
        "explicit_level": None,
        "donor_description": None,
    }
    safety = photo_gallery.DEFAULT_SAFETY
    if donor_status["is_donor"]:
        safety = f"donor-authorized explicit level: {donor_status['explicit_level']}"
    entry = photo_gallery.add_image_entry(
        image_id=image_id,
        filename=filename,
        description=description,
        tags=(tags or []) + [mood_key],
        style="photo-realistic, moody, grounded",
        mood=mood_key,
        prompt=prompt,
        resolution="1024x1024",
        model="stable-diffusion-v2",
        platforms=platforms or DEFAULT_PLATFORMS,
        safety=safety,
        integrity="autogenerated",
        extra_metadata={
            "visual_state": visual_state,
            "donor_status": donor_status,
        },
    )

    provider_result: Dict[str, Any] = {}
    if provider is not None:
        provider_result = provider(prompt, provider_kwargs or {})

    return {
        "entry": entry,
        "prompt": prompt,
        "provider_result": provider_result,
    }


def sample_image_provider(prompt: str, provider_kwargs: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    """Sample provider adapter that returns a mock response."""
    return {
        "provider": "mock",
        "prompt": prompt,
        "provider_kwargs": provider_kwargs or {},
        "status": "queued",
    }


def create_today_photo(
    user_id: Optional[str] = None,
    provider: Optional[ImageProvider] = None,
    provider_kwargs: Optional[Dict[str, Any]] = None,
    platforms: Optional[List[str]] = None,
    tags: Optional[List[str]] = None,
    extra_context: Optional[str] = None,
) -> Dict[str, Any]:
    """Generate a new photo using Lyra's predetermined daily mood."""
    mood = Lyra_Soul.get_daily_mood()
    return generate_autonomous_photo(
        mood=mood,
        user_id=user_id,
        provider=provider,
        provider_kwargs=provider_kwargs,
        platforms=platforms,
        tags=tags,
        extra_context=extra_context,
    )
